version: '2'
services:
  logstash:
    restart: always
    links:
    - elasticsearch:elasticsearch
    volumes:
      - ./logstash-config:/etc/logstash
    command:
    - logstash
    - -r
    - -f
    - /etc/logstash
    image: docker.elastic.co/logstash/logstash:6.4.2
    ports:
      - "8080:8080"

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:6.4.2
    links:
    - elasticsearch:elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1